Repository wllfaria/darkmoon, pull requests merged in 2020-11, with the labels that each got.

#52 ci(web): adding build CI
  .github/workflows/web-build.yml
Labels: Type: ci

#55 docs: updating main repository readme
  README.md
Labels: Effort: 1, Priority: now, Type: docs

#50 feat(web): adding themes and basic project structure
  web/.editorconfig
  web/.eslintrc.js
  web/package.json
  web/prettier.config.js
  web/public/index.html
  web/src/App.tsx
  web/src/components/SaleWarning.tsx
  web/src/hooks/useGetRequest.ts
  web/src/pages/HomePage.tsx
  web/src/services/axios.ts
  web/src/states/appThemeState.tsx
  web/src/styles/Globalstyle.ts
  web/src/styles/index.ts
  web/src/styles/themes/darkTheme.ts
  web/src/styles/themes/fixedStyles.ts
  web/src/styles/themes/index.ts
  web/src/styles/themes/lightTheme.ts
  web/tsconfig.json
  web/typings.d.ts
  web/yarn.lock
Labels: Effort: 3, Priority: medium, Type: feature

#57 feat(web): adding react-helmet to handle html head changes
  web/package.json
  web/src/components/HeadHelmet.tsx
  web/yarn.lock
Labels: Effort: 2, Priority: medium, Type: feature

#58 feat(web): adding storybook for creating a design system
  web/.storybook/main.js
  web/.storybook/manager.js
  web/.storybook/preview.js
  web/package.json
  web/src/components/SaleWarning.stories.mdx
  web/src/components/SaleWarning.tsx
  web/src/pages/HomePage.tsx
  web/tsconfig.json
  web/yarn.lock
Labels: Effort: 3, Priority: medium, Type: feature

#64 ci(web): adding ci for storybook build steps
  .github/workflows/node.js.yml
Labels: Effort: 1, Priority: medium, Type: ci

#61 feat(web): product card implementation
  .gitignore
  web/.editorconfig
  web/.eslintrc.js
  web/public/index.html
  web/src/components/Button/Button.stories.mdx
  web/src/components/Button/index.tsx
  web/src/components/Button/styles.ts
  web/src/components/ProductCard/ProductCard.stories.mdx
  web/src/components/ProductCard/index.tsx
  web/src/components/ProductCard/styles.ts
  web/src/components/ProductCardList/ProductCardList.stories.mdx
  web/src/components/ProductCardList/index.tsx
  web/src/components/ProductCardList/styles.ts
  web/src/components/SaleWarning.tsx
  web/src/components/SaleWarning/SaleWarning.stories.mdx
  web/src/components/SaleWarning/index.tsx
  web/src/components/SaleWarning/styles.ts
  web/src/mocks/data/products.json
  web/src/pages/HomePage.tsx
  web/src/styles/GlobalComponents.ts
  web/src/styles/Globalstyle.ts
  web/src/styles/themes/darkTheme.ts
  web/src/styles/themes/fixedStyles.ts
  web/src/styles/themes/lightTheme.ts
  web/src/types/models/Product.ts
  web/src/types/models/ProductImage.ts
  web/typings.d.ts
Labels: Effort: 8, Priority: medium, Type: feature

#69 feat(storybook): adding netlify cd
  web/.gitignore
  web/package.json
Labels: Effort: 5, Priority: medium, Type: ci

#68 feat(server): adding product crud api
  server/mockData/mockProduct.json
  server/package-lock.json
  server/package.json
  server/serverless.ts
  server/serverless/functions.ts
  server/serverless/resources.ts
  server/src/controllers/auth.ts
  server/src/controllers/product.ts
  server/src/handlers/product.ts
  server/src/models/product.ts
  server/src/typings/product.ts
  server/src/utils/lambdaUtils.ts
  server/src/utils/lambdaWrapper.ts
  server/tsconfig.json
Labels: Effort: 8, Priority: medium, Type: feature

#71 ci: adding github codeql analysis
  .github/workflows/codeql-analysis.yml
Labels: Effort: 1, Priority: low, Type: ci
